-------------------------------------------------------------------------------
Test set: com.tensquare.user.CrawlerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.131 s <<< FAILURE! - in com.tensquare.user.CrawlerTest
test(com.tensquare.user.CrawlerTest)  Time elapsed: 1.137 s  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at com.tensquare.user.CrawlerTest.test(CrawlerTest.java:29)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused: connect
	at com.tensquare.user.CrawlerTest.test(CrawlerTest.java:29)
Caused by: java.net.ConnectException: Connection refused: connect
	at com.tensquare.user.CrawlerTest.test(CrawlerTest.java:29)

